steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/healthcare-rag-chatbot:latest', '-f', 'Dockerfile.ollama', '.']
images:
  - 'gcr.io/$PROJECT_ID/healthcare-rag-chatbot:latest'
